[greeter]
background=/usr/share/backgrounds/btw-wallpaper.png
theme-name=Windows-7
icon-theme-name=Windows-7-icons
font-name=Sans 11
clock-format=%H:%M  %A %d %B
indicators=~host;~spacer;~clock;~spacer;~session;~power
position=50%,center 55%,center
