#!/bin/sh
set -e

lb config noauto \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --debian-installer none \
    --apt-indices false \
    --security true \
    --updates true \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-binary-security "http://security.debian.org/debian-security/" \
    --iso-application "Better Than Windows OS" \
    --iso-volume "BTW_OS" \
    --iso-preparer "Better Than Windows OS build kit" \
    --iso-publisher "Better Than Windows OS" \
    --bootappend-live "boot=live components quiet splash hostname=better-than-windows username=user user-fullname='Better Than Windows User'" \
    "${@}"
